### ISSUE TITLE
Keep getting error at npm start - any insight? 

### ISSUE THREAD

**Issue by LACoderDeBH** [insidesherpa/shiptivitas-1#3]
tried npm install, and update but no luck 

<img width="893" alt="Screen Shot 2019-04-01 at 12 34 42 PM" src="https://user-images.githubusercontent.com/28251592/55354436-9a1f5a00-547a-11e9-987b-84071be8282b.png">

**Comment by juliusarden** [comment]
Looking from your error message, there is some problem with your HOST environment variable.
I found a page that has similar issue https://medium.com/@choy/fixing-create-react-app-when-npm-fails-to-start-because-your-host-environment-variable-is-being-4c8a9fa0b461

I tried some versions of node (8.16.0, 11.10.0 and 11.14.0) and they all works fine. Try updating your node version. To make it easier, you can try using NVM https://github.com/nvm-sh/nvm to manage node and npm version
Here is my node and npm version.
```
Juliuss:shiptivitas-1 jtio$ node -v
v8.16.0
Juliuss:shiptivitas-1 jtio$ npm -v
6.4.1
```

**Comment by LACoderDeBH** [comment]
Thank you! The solution in the medium article did the trick.
